[tool.poetry]
name = "workspace"
version = "0.1.0"
description = ""
authors = ["ITHwang <hwangintech@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies] # main dependency group
python = "^3.11"

[tool.poetry.group.dev.dependencies]

[tool.poetry.group.test.dependencies]

[tool.poetry.group.docs.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
